version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_school
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schooldb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - school-network

  school-app:
    build: .
    container_name: school_app
    depends_on:
      - mysql
    ports:
      - "8082:8080"
    networks:
      - school-network

volumes:
  mysql_data:

networks:
  school-network:
